FROM node:20-slim as builder
RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

# Build the client UI
COPY ./client /app/client
WORKDIR /app/client
RUN npm install && npm run build

FROM python:3.13-slim-bullseye as python_builder

WORKDIR /app

# copy requirements file and install dependencies
COPY ./server/requirements.txt /app/requirements.txt
RUN python3.13 -m pip install -r /app/requirements.txt

FROM python:3.13-slim-bullseye
RUN python3.13 -m pip install --upgrade pip

ENV PYTHONPATH="/app"

RUN cp ./server/requirements.txt /app/requirements.txt && \
    python3.13 -m pip install -r /app/requirements.txt && \
    rm -f /app/requirements.txt

# copy files
COPY ./server/304/ /app/

COPY --from=python_builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /app/client/dist /app/client
EXPOSE 80

CMD ["python3.13", "/app/__main__.py", "--version", "1.0.0"]
