FROM python:3.12.2-slim-bullseye
RUN python3.12 -m pip install --upgrade pip
ENV PYTHONPATH="/app"

WORKDIR /app

# copy requirements file and install dependencies
COPY ./server/requirements.txt /app/requirements.txt
RUN python3.12 -m pip install -r /app/requirements.txt
RUN rm -f /app/requirements.txt

# copy files
COPY ./server/304/ /app/

EXPOSE 80

CMD ["python3.12", "/app/__main__.py", "--version", "1.0.0"]
