name: Build Docker Image

on:
  push:
    branches:
      - main
      - development

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t 304-game-server:latest .

    - name: Print success message
      run: echo "Docker image built successfully!"